### ISSUE TITLE
Incorrect calibration parameter

### ISSUE THREAD

**Issue by arubin** [msardonini/oakd_isaac_ros#1]
https://github.com/msardonini/oakd_isaac_ros/blob/020eca06b39115d6398b30f2b2ccd28b4e8ace77/src/oakd_s2/src/stereo_calibration_ros_convert.hpp#L36

This looks like a typo - I think right cam calibration should be referencing R1 (not R0)

**Comment by msardonini** [comment]
Thanks for sharing!

Looks like a classic copy/paste error :grimacing: whoops.

Fixed in [this commit](https://github.com/msardonini/oakd_isaac_ros/commit/1c54cd267165df32e1402747f5b1d11eb38684af)
